name: Feature Request
description: Suggest a new feature or enhancement for cdp-rs
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
      
  - type: textarea
    id: example
    attributes:
      label: Example API Design (Optional)
      description: If applicable, show us what the API might look like
      render: rust
      placeholder: |
        // Example of how the feature might be used
        page.new_feature().await?;
    validations:
      required: false
      
  - type: dropdown
    id: scope
    attributes:
      label: Which crate does this feature apply to?
      options:
        - cdp-core
        - cdp-protocol
        - Both
        - Other
    validations:
      required: true
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Are you willing to contribute this feature?
      options:
        - label: Yes, I'd like to implement this feature
        - label: I can help with testing
        - label: I can help with documentation
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false
